FROM fedora:latest
RUN yum install -y golang git trousers-devel cabextract
COPY . /home
WORKDIR /home/server
# This grabs the current set of TPM certificates
RUN go generate ./...
RUN go build

FROM registry.access.redhat.com/ubi8/ubi-minimal
RUN microdnf install trousers-lib
COPY --from=0 /home/server/server /bin/server
EXPOSE 8080
USER 1000
CMD ["/bin/server"]
